server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      returnErrors: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true