management:
  endpoints:
    web:
      exposure:
        include: "health, info, mappings, metrics, loggers, shutdown, pause, resume"

server:
  port: 8091

jwt:
  secret: minha-secret
  expiration: 10000

spring:
  application:
    name: vehicle
  profiles:
    active: development
  main:
    web-application-type: reactive
  data:
    mongodb:
      database: aatruckdetailDB
      uri: mongodb+srv://aatruckdetail:i9XYt1q2xIIxvmaE@aatruckcluster.mysmi.mongodb.net/?retryWrites=true&w=majority